name: Deploy to Azure Storage

on:
  push:
    branches:
      - main  # Ensure this matches your pushed branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Setup Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '20'  # Set to the latest version

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Azure Storage Upload
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch -d '$web' -s './dist' --account-name astroblogstorage
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
